# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sayan/Documents/gic2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sayan/Documents/gic2/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/sayan/Documents/gic2/build && $(CMAKE_COMMAND) -E cmake_progress_start /home/sayan/Documents/gic2/build/CMakeFiles /home/sayan/Documents/gic2/build/src/CMakeFiles/progress.marks
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f CMakeFiles/Makefile2 src/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sayan/Documents/gic2/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f CMakeFiles/Makefile2 src/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f CMakeFiles/Makefile2 src/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f CMakeFiles/Makefile2 src/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/sayan/Documents/gic2/build && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
src/CMakeFiles/GIComplex.dir/rule:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f CMakeFiles/Makefile2 src/CMakeFiles/GIComplex.dir/rule
.PHONY : src/CMakeFiles/GIComplex.dir/rule

# Convenience name for target.
GIComplex: src/CMakeFiles/GIComplex.dir/rule
.PHONY : GIComplex

# fast build rule for target.
GIComplex/fast:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f src/CMakeFiles/GIComplex.dir/build.make src/CMakeFiles/GIComplex.dir/build
.PHONY : GIComplex/fast

ANNSearchSampling.o: ANNSearchSampling.cpp.o
.PHONY : ANNSearchSampling.o

# target to build an object file
ANNSearchSampling.cpp.o:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f src/CMakeFiles/GIComplex.dir/build.make src/CMakeFiles/GIComplex.dir/ANNSearchSampling.cpp.o
.PHONY : ANNSearchSampling.cpp.o

ANNSearchSampling.i: ANNSearchSampling.cpp.i
.PHONY : ANNSearchSampling.i

# target to preprocess a source file
ANNSearchSampling.cpp.i:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f src/CMakeFiles/GIComplex.dir/build.make src/CMakeFiles/GIComplex.dir/ANNSearchSampling.cpp.i
.PHONY : ANNSearchSampling.cpp.i

ANNSearchSampling.s: ANNSearchSampling.cpp.s
.PHONY : ANNSearchSampling.s

# target to generate assembly for a file
ANNSearchSampling.cpp.s:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f src/CMakeFiles/GIComplex.dir/build.make src/CMakeFiles/GIComplex.dir/ANNSearchSampling.cpp.s
.PHONY : ANNSearchSampling.cpp.s

DijkstraAlgorithm.o: DijkstraAlgorithm.cpp.o
.PHONY : DijkstraAlgorithm.o

# target to build an object file
DijkstraAlgorithm.cpp.o:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f src/CMakeFiles/GIComplex.dir/build.make src/CMakeFiles/GIComplex.dir/DijkstraAlgorithm.cpp.o
.PHONY : DijkstraAlgorithm.cpp.o

DijkstraAlgorithm.i: DijkstraAlgorithm.cpp.i
.PHONY : DijkstraAlgorithm.i

# target to preprocess a source file
DijkstraAlgorithm.cpp.i:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f src/CMakeFiles/GIComplex.dir/build.make src/CMakeFiles/GIComplex.dir/DijkstraAlgorithm.cpp.i
.PHONY : DijkstraAlgorithm.cpp.i

DijkstraAlgorithm.s: DijkstraAlgorithm.cpp.s
.PHONY : DijkstraAlgorithm.s

# target to generate assembly for a file
DijkstraAlgorithm.cpp.s:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f src/CMakeFiles/GIComplex.dir/build.make src/CMakeFiles/GIComplex.dir/DijkstraAlgorithm.cpp.s
.PHONY : DijkstraAlgorithm.cpp.s

FibonacciHeap.o: FibonacciHeap.cpp.o
.PHONY : FibonacciHeap.o

# target to build an object file
FibonacciHeap.cpp.o:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f src/CMakeFiles/GIComplex.dir/build.make src/CMakeFiles/GIComplex.dir/FibonacciHeap.cpp.o
.PHONY : FibonacciHeap.cpp.o

FibonacciHeap.i: FibonacciHeap.cpp.i
.PHONY : FibonacciHeap.i

# target to preprocess a source file
FibonacciHeap.cpp.i:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f src/CMakeFiles/GIComplex.dir/build.make src/CMakeFiles/GIComplex.dir/FibonacciHeap.cpp.i
.PHONY : FibonacciHeap.cpp.i

FibonacciHeap.s: FibonacciHeap.cpp.s
.PHONY : FibonacciHeap.s

# target to generate assembly for a file
FibonacciHeap.cpp.s:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f src/CMakeFiles/GIComplex.dir/build.make src/CMakeFiles/GIComplex.dir/FibonacciHeap.cpp.s
.PHONY : FibonacciHeap.cpp.s

PointSet.o: PointSet.cpp.o
.PHONY : PointSet.o

# target to build an object file
PointSet.cpp.o:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f src/CMakeFiles/GIComplex.dir/build.make src/CMakeFiles/GIComplex.dir/PointSet.cpp.o
.PHONY : PointSet.cpp.o

PointSet.i: PointSet.cpp.i
.PHONY : PointSet.i

# target to preprocess a source file
PointSet.cpp.i:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f src/CMakeFiles/GIComplex.dir/build.make src/CMakeFiles/GIComplex.dir/PointSet.cpp.i
.PHONY : PointSet.cpp.i

PointSet.s: PointSet.cpp.s
.PHONY : PointSet.s

# target to generate assembly for a file
PointSet.cpp.s:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f src/CMakeFiles/GIComplex.dir/build.make src/CMakeFiles/GIComplex.dir/PointSet.cpp.s
.PHONY : PointSet.cpp.s

SimpleGraph.o: SimpleGraph.cpp.o
.PHONY : SimpleGraph.o

# target to build an object file
SimpleGraph.cpp.o:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f src/CMakeFiles/GIComplex.dir/build.make src/CMakeFiles/GIComplex.dir/SimpleGraph.cpp.o
.PHONY : SimpleGraph.cpp.o

SimpleGraph.i: SimpleGraph.cpp.i
.PHONY : SimpleGraph.i

# target to preprocess a source file
SimpleGraph.cpp.i:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f src/CMakeFiles/GIComplex.dir/build.make src/CMakeFiles/GIComplex.dir/SimpleGraph.cpp.i
.PHONY : SimpleGraph.cpp.i

SimpleGraph.s: SimpleGraph.cpp.s
.PHONY : SimpleGraph.s

# target to generate assembly for a file
SimpleGraph.cpp.s:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f src/CMakeFiles/GIComplex.dir/build.make src/CMakeFiles/GIComplex.dir/SimpleGraph.cpp.s
.PHONY : SimpleGraph.cpp.s

gic.o: gic.cpp.o
.PHONY : gic.o

# target to build an object file
gic.cpp.o:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f src/CMakeFiles/GIComplex.dir/build.make src/CMakeFiles/GIComplex.dir/gic.cpp.o
.PHONY : gic.cpp.o

gic.i: gic.cpp.i
.PHONY : gic.i

# target to preprocess a source file
gic.cpp.i:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f src/CMakeFiles/GIComplex.dir/build.make src/CMakeFiles/GIComplex.dir/gic.cpp.i
.PHONY : gic.cpp.i

gic.s: gic.cpp.s
.PHONY : gic.s

# target to generate assembly for a file
gic.cpp.s:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f src/CMakeFiles/GIComplex.dir/build.make src/CMakeFiles/GIComplex.dir/gic.cpp.s
.PHONY : gic.cpp.s

gic/FlagComplex.o: gic/FlagComplex.cpp.o
.PHONY : gic/FlagComplex.o

# target to build an object file
gic/FlagComplex.cpp.o:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f src/CMakeFiles/GIComplex.dir/build.make src/CMakeFiles/GIComplex.dir/gic/FlagComplex.cpp.o
.PHONY : gic/FlagComplex.cpp.o

gic/FlagComplex.i: gic/FlagComplex.cpp.i
.PHONY : gic/FlagComplex.i

# target to preprocess a source file
gic/FlagComplex.cpp.i:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f src/CMakeFiles/GIComplex.dir/build.make src/CMakeFiles/GIComplex.dir/gic/FlagComplex.cpp.i
.PHONY : gic/FlagComplex.cpp.i

gic/FlagComplex.s: gic/FlagComplex.cpp.s
.PHONY : gic/FlagComplex.s

# target to generate assembly for a file
gic/FlagComplex.cpp.s:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f src/CMakeFiles/GIComplex.dir/build.make src/CMakeFiles/GIComplex.dir/gic/FlagComplex.cpp.s
.PHONY : gic/FlagComplex.cpp.s

gic/GIComplex.o: gic/GIComplex.cpp.o
.PHONY : gic/GIComplex.o

# target to build an object file
gic/GIComplex.cpp.o:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f src/CMakeFiles/GIComplex.dir/build.make src/CMakeFiles/GIComplex.dir/gic/GIComplex.cpp.o
.PHONY : gic/GIComplex.cpp.o

gic/GIComplex.i: gic/GIComplex.cpp.i
.PHONY : gic/GIComplex.i

# target to preprocess a source file
gic/GIComplex.cpp.i:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f src/CMakeFiles/GIComplex.dir/build.make src/CMakeFiles/GIComplex.dir/gic/GIComplex.cpp.i
.PHONY : gic/GIComplex.cpp.i

gic/GIComplex.s: gic/GIComplex.cpp.s
.PHONY : gic/GIComplex.s

# target to generate assembly for a file
gic/GIComplex.cpp.s:
	cd /home/sayan/Documents/gic2/build && $(MAKE) -f src/CMakeFiles/GIComplex.dir/build.make src/CMakeFiles/GIComplex.dir/gic/GIComplex.cpp.s
.PHONY : gic/GIComplex.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GIComplex"
	@echo "... ANNSearchSampling.o"
	@echo "... ANNSearchSampling.i"
	@echo "... ANNSearchSampling.s"
	@echo "... DijkstraAlgorithm.o"
	@echo "... DijkstraAlgorithm.i"
	@echo "... DijkstraAlgorithm.s"
	@echo "... FibonacciHeap.o"
	@echo "... FibonacciHeap.i"
	@echo "... FibonacciHeap.s"
	@echo "... PointSet.o"
	@echo "... PointSet.i"
	@echo "... PointSet.s"
	@echo "... SimpleGraph.o"
	@echo "... SimpleGraph.i"
	@echo "... SimpleGraph.s"
	@echo "... gic.o"
	@echo "... gic.i"
	@echo "... gic.s"
	@echo "... gic/FlagComplex.o"
	@echo "... gic/FlagComplex.i"
	@echo "... gic/FlagComplex.s"
	@echo "... gic/GIComplex.o"
	@echo "... gic/GIComplex.i"
	@echo "... gic/GIComplex.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/sayan/Documents/gic2/build && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

